config-sources:

- name: bosh-lab-yaml
  type: file
  params:
    path: ~/deployments/bosh-1/no-commit/creds.yml

- name: bosh-lab-credhub
  type: credhub
  config: bosh-lab-yaml
  params:
    client_id: something
    client_secret: somethingelse
    username: director_to_credhub
    password: ((/uaa_clients_director_to_credhub))
    server: https://192.168.3.11:4343
    ca_cert: ((/credhub-ca-cert.certificate))
    skip_tls_validation: false

- name: concourse-lab-credhub
  type: credhub
  config: bosh-lab-credhub
  params:
    client_id: ((/credhub-client))
    client_secret: ((/credhub-secret))
    server: https://192.168.0.6:8844
    ca_cert: ((/credhub-ca-cert.certificate))
    skip_tls_validation: false

environments:

- name: lab
  processes:
  
  - name: fly
    config: bosh-lab-credhub
    path: fly
    args:
    - -t
    - main
    - login
    - -u
    - atc
    - -p ((/bosh-1/concourse/atc_basic_auth_password))

  - name: bosh-credhub
    config: bosh-lab-yaml
    path: credhub
    args:
    - login
    env:
      CREDHUB_CLIENT: ((/credhub-client))
      CREDHUB_SECRET: ((/credhub-secret))
      CREDHUB_CA_CERT: ((/credhub-ca-cert.certificate))
      CREDHUB_SERVER: https://192.168.0.6:8844

  - name: concourse-credhub
    config: bosh-lab-credhub
    path: credhub
    args:
    - login
    env:
      CREDHUB_CLIENT: ((/credhub-client))
      CREDHUB_SECRET: ((/credhub-secret))
      CREDHUB_CA_CERT: ((/credhub-ca-cert.certificate))
      CREDHUB_SERVER: https://192.168.0.10:8844

packages:

- name: fly
  version: 3.14.1
  alias: fly
  platforms:
  - name: linux
    download:
      url: https://github.com/concourse/concourse/releases/download/v((version))/fly_linux_amd64
      output: fly_((version))_linux_amd64
  - name: windows
    download:
      url: https://github.com/concourse/concourse/releases/download/v((version))/fly_windows_amd64.exe
      output: fly_((version))_windows_amd64
  - name: darwin
    download:
      url: https://github.com/concourse/concourse/releases/download/v((version))/fly_darwin_amd64
      output: fly_((version))_darwin_amd64

- name: bbl
  version: 6.7.15
  alias: bbl
  platforms:
  - name: linux
    download:
      url: https://github.com/cloudfoundry/bosh-bootloader/releases/download/v((version))/bbl-v((version))_linux_x86-64      
      output: bbl-v((version))_linux_x86-64
  - name: windows
    download:
      url: https://github.com/cloudfoundry/bosh-bootloader/releases/download/v((version))/bbl-v((version))_windows.exe
      output: bbl-v((version))_windows.exe
  - name: darwin
    download:
      url: https://github.com/cloudfoundry/bosh-bootloader/releases/download/v((version))/bbl-v((version))_osx
      output: bbl-v((version))_osx

- name: bosh
  version: 3.0.1
  alias: bosh
  platforms:
  - name: linux
    download:
      url: https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-((version))-linux-amd64
      output: bosh-cli-((version))-linux-amd64
  - name: windows
    download:
      url: https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-((version))-windows-amd64.exe
      output: bosh-cli-((version))-windows-amd64.exe
  - name: darwin
    download:
      url: https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-((version))-darwin-amd64
      output: bosh-cli-((version))-darwin-amd64

- name: credhub
  version: 1.7.6
  alias: credhub
  platforms:
  - name: linux
    download: 
      url: https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/((version))/credhub-linux-((version)).tgz      
      output: credhub-((version))-linux.tgz
  - name: darwin
    download: 
      url: https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/((version))/credhub-darwin-((version)).tgz      
      output: credhub-((version))-darwin.tgz
  - name: windows
    download: 
      url: https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/((version))/credhub-windows-((version)).tgz      
      output: credhub-((version))-windows.tgz

- name: cf
  version: 6.37.0
  alias: cf
  platforms:
  - name: linux
    download:
      url: https://packages.cloudfoundry.org/stable?release=linux64-binary&version=((version))&source=github-rel
      output: cf-cli_((version))_linux_x86-64.tgz
    extract:
      filter: cf
      output: cf_((version))_linux
  - name: darwin
    download:
      url: https://packages.cloudfoundry.org/stable?release=macosx64-binary&version=((version))&source=github-rel
      output: cf-cli_6.37.0_osx.tgz
    extract:
      filter: cf
      output: cf_((version))_darwin
  - name: windows
    download:
      url: https://packages.cloudfoundry.org/stable?release=windows64-exe&version=((version))&source=github-rel      
      output: cf-cli_((version))_winx64.zip
    extract:
      filter: cf.exe
      output: cf_((version))_winx64.exe

- name: bbr
  version: 1.2.4
  alias: bbr
  platforms:
  - name: linux
    download:
      url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.2.4/bbr-1.2.4.tar      
      output: bbr-((version)).tar
    extract:
      filter: bbr
      output: bbr-((version))-linux
  - name: darwin
    download:
      url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.2.4/bbr-1.2.4.tar      
      output: bbr-((version)).tar
    extract:
      filter: bbr-mac
      output: bbr-((version))-darwin