stores:

- name: bosh-lab-yaml
  type: file
  params:
    path: state/vars/director-vars-store.yml

- name: bosh-lab-credhub
  type: credhub
  stores: 
  - bosh-lab-yaml
  params:
    client_id: director_to_credhub
    client_secret: ((uaa_clients_director_to_credhub))
    username:
    password:
    server: https://192.168.3.11:4343
    ca_cert: ((credhub-ca-cert.certificate))
    skip_tls_validation: false

- name: concourse-lab-credhub
  type: credhub
  stores: 
  - bosh-lab-credhub
  params:
    client_id: ((credhub-client))
    client_secret: ((credhub-secret))
    server: https://192.168.0.6:8844
    ca_cert: ((credhub-ca-cert.certificate))
    skip_tls_validation: false

processes:
- name: fly
  stores: 
  - bosh-lab-credhub
  path: fly
  args:
  - -t
  - main
  - login
  - -u
  - ((/bosh-lab/concourse/atc_basic_auth.username))
  - -p 
  - ((/bosh-lab/concourse/atc_basic_auth.password))

- name: bosh-credhub
  stores: 
  - bosh-lab-yaml
  path: credhub
  args:
  - login
  env:
    CREDHUB_CLIENT: ((credhub-client))
    CREDHUB_SECRET: ((credhub-secret))
    CREDHUB_CA_CERT: ((credhub-ca-cert.certificate))
    CREDHUB_SERVER: https://192.168.0.6:8844

- name: concourse-credhub
  stores: 
  - bosh-lab-credhub
  path: credhub
  args:
  - login
  env:
    CREDHUB_CLIENT: ((credhub-client))
    CREDHUB_SECRET: ((credhub-secret))
    CREDHUB_CA_CERT: ((credhub-ca-cert.certificate))
    CREDHUB_SERVER: https://192.168.0.10:8844