name: test
version: 1.0.0
targets:
- platform: windows
  architecture: amd64
  tasks:
  - download:
      url: https://somesite.net/d/test
      out: test-windows-1.0.0.tgz
  - extract:
      archive: test-windows-1.0.0.tgz
      destination: .
  - move: 
      source: test.exe
      destination: test-windows-1.0.0.exe
      